channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda
dependencies:
  - pip
  - python=3.9
  - pytorch-cuda=11.8
  - torchvision
  - pandas
  - wandb
  - pip:
    - requests
    - opencv-python
    - monai[skimage, scipy, tqdm, pyyaml, matplotlib, einops]